set(_CATKIN_CURRENT_PACKAGE "camera_tracker")
set(camera_tracker_VERSION "0.0.0")
set(camera_tracker_MAINTAINER "revanthkonda <revanthkonda@todo.todo>")
set(camera_tracker_PACKAGE_FORMAT "1")
set(camera_tracker_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(camera_tracker_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(camera_tracker_BUILDTOOL_DEPENDS "catkin")
set(camera_tracker_BUILDTOOL_EXPORT_DEPENDS )
set(camera_tracker_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(camera_tracker_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(camera_tracker_TEST_DEPENDS )
set(camera_tracker_DOC_DEPENDS )
set(camera_tracker_DEPRECATED "")